name: publish

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to platforms'
        required: true
        default: true
        type: boolean
      version_name:
        description: 'Version Name'
        required: true
        default: 'version'
        type: string
      platform_changelog:
        description: 'Platform Changelog'
        required: true
        default: '[Click here to open the **full changelog**]()'
        type: string
      changelog:
        description: 'Github and Discord Changelog'
        required: true
        default: 'No changelog provided'
        type: string
      full_changelog:
        description: 'Full Changelog Link'
        required: true
        default: 'https://github.com/Mat0u5/LifeSeries'
        type: string
      version_type:
        description: 'Version type'
        required: true
        default: 'STABLE'
        type: choice
        options:
          - STABLE
          - BETA
          - ALPHA
      ping:
        description: 'Ping'
        required: true
        default: true
        type: boolean

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build


      - name: Commit message newline
        run: |
          COMMIT_MESSAGE_RAW="${{ github.event.inputs.changelog }}"
          COMMIT_MESSAGE_NEWLINE=$(echo "$COMMIT_MESSAGE_RAW" | sed 's/\\n/\'$'\n''/g')
          echo "COMMIT_MESSAGE_NEWLINE<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MESSAGE_NEWLINE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Commit message line break
        run: |
          COMMIT_MESSAGE_RAW="${{ github.event.inputs.platform_changelog }}"
          COMMIT_MESSAGE_BR=$(echo "$COMMIT_MESSAGE_RAW" | sed 's/\\n/<br>/g')
          echo "COMMIT_MESSAGE_BR=$COMMIT_MESSAGE_BR" >> $GITHUB_ENV

      - name: Publish to Modrinth and Curseforge (Sequential)
        if: ${{ inputs.publish }}
        run: |
          # Define version order explicitly to match your delay preferences
          VERSIONS=("1.21" "1.21.2" "1.21.4" "1.21.5" "1.21.6")

          for version in "${VERSIONS[@]}"; do
            if [ -d "./versions/$version" ]; then
              echo "Publishing version $version..."
              (cd "./versions/$version" && ../../gradlew publishMods)
              echo "✅ Successfully published $version"
              sleep 5
            else
              echo "⚠️  Version directory $version not found, skipping"
            fi
          done
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          CHANGELOG: ${{ env.COMMIT_MESSAGE_BR }}
          VERSION_TYPE: ${{ github.event.inputs.version_type }}
          DEV_BUILD: false

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Built JARs
          path: |
            ./versions/**/build/libs/*.jar

      - name: Filter non-source JAR files
        id: filtered_jars
        run: |
          jars=$(find ./versions/**/build/libs/ -type f -name "*.jar" ! -name "*-sources.jar")
          echo "jar_files<<EOF" >> $GITHUB_OUTPUT
          echo "$jars" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate Version Tag
        id: version
        run: |
          # Generate a version based on current date and commit hash
          VERSION="$(echo ${{ github.event.inputs.version_name }})"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Generated version: $VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

      - name: Create GitHub Release with JARs
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          tag_name: ${{ steps.version.outputs.version }}
          name: Version Control v.${{ steps.version.outputs.version }}
          body: |
            ${{ env.COMMIT_MESSAGE_NEWLINE }}
          draft: false
          prerelease: false
          files: |
            ${{ steps.filtered_jars.outputs.jar_files }}

      - name: Get Title
        id: discord_title
        run: |
          if [ "${{ github.event.inputs.ping }}" = "false" ]; then
            echo "MESSAGE_TITLE=*Ping Skipped.*" >> $GITHUB_ENV
          else
            echo "MESSAGE_TITLE=<@&1346438113169510421>" >> $GITHUB_ENV
          fi

      - name: Discord Message
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_ANNOUNCEMENTS }}
          method: POST
          payload: '{ "content": "${{ env.MESSAGE_TITLE }}\n## [Version `${{ github.event.inputs.version_name }}` is out!](https://modrinth.com/mod/life-series/versions)", "embeds": [{"author": {"name": "Mat0u5","url": "https://github.com/Mat0u5","icon_url": "https://github.com/Mat0u5.png"},"description": "\nChangelog:\n```\n${{ github.event.inputs.changelog }}```\n[Click here to open the **full changelog**](${{ github.event.inputs.full_changelog }})", "color": 5315202 }] }'